name = "tianliao-blog"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "BLOG_KV"
id = "ee0a4f0df6b94c41911ad0cd62add03a"

[[r2_buckets]]
binding = "IMG_BUCKET"
bucket_name = "img"

[vars]
SITE_TITLE = "天聊博客"
SITE_DESCRIPTION = "一个基于 Cloudflare Workers 的博客"
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin123"

[triggers]
crons = ["0 2 * * *"]
